name = "Scanivalve"
uuid = "4fb5c015-4516-465f-8a65-a29a7c83b06b"
authors = ["Paulo Jos√© Saiz Jabardo <pjabardo@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
